services:
  php:
    environment:
      SERVER_NAME: "https://local.julienbonnier.dev"
      CADDY_GLOBAL_OPTIONS: |
        https_port 4443
        http_port 8080
        skip_install_trust
      CADDY_SERVER_EXTRA_DIRECTIVES: |
        tls /etc/caddy/certs/server.crt /etc/caddy/certs/server.key
    extra_hosts:
      - "local.julienbonnier.dev:127.0.0.1"
      - "local.julienbonnier.dev:::1"
    volumes:
      - ./src:/srv/app
      - ~/.tls/local-dev/server.crt:/etc/caddy/certs/server.crt:ro
      - ~/.tls/local-dev/server.key:/etc/caddy/certs/server.key:ro
  php-cli:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php_dev
    command:
      - sleep
      - infinity
    stop_signal: SIGKILL
    healthcheck:
      test: exit 0
    volumes:
      - ./src:/srv/app
    networks:
      - php
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: wordpressdb
      WP_ENV: development
      WP_HOME: https://local.julienbonnier.dev
      WP_SITEURL: https://local.julienbonnier.dev/wp
      # This is used for Xdebug step debugging with PHP CLI and should match the "Name" of the server used in
      # PhpStorm server configuration: Settings > PHP > Servers > Name.
      # Note: When configured, it will also be used when step debugging from a browser but is necessary only for CLI.
      PHP_IDE_CONFIG: serverName=local (docker)
    env_file:
      - src/.env
