services:
  php:
    environment:
      SERVER_NAME: "https://local.julienbonnier.dev"
      CADDY_GLOBAL_OPTIONS: |
        https_port 4443
        http_port 8080
        skip_install_trust
      CADDY_SERVER_EXTRA_DIRECTIVES: |
        tls /etc/caddy/certs/server.crt /etc/caddy/certs/server.key
                
        reverse_proxy /app/themes/sage/public/build/* http://vite:3000 {
          flush_interval -1
          header_down Cache-Control no-cache
          header_down Pragma no-cache
          header_up Upgrade {http.request.header.Upgrade}
          header_up Connection {http.request.header.Connection}
        }
    extra_hosts:
      - "local.julienbonnier.dev:127.0.0.1"
      - "local.julienbonnier.dev:::1"
    volumes:
      - ./src:/srv/app
      - ~/.tls/local-dev/server.crt:/etc/caddy/certs/server.crt:ro
      - ~/.tls/local-dev/server.key:/etc/caddy/certs/server.key:ro
  php-cli:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php_dev
    command:
      - sleep
      - infinity
    stop_signal: SIGKILL
    healthcheck:
      test: exit 0
    volumes:
      - ./src:/srv/app
    networks:
      - php
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: wordpressdb
      WP_ENV: development
      WP_HOME: https://local.julienbonnier.dev
      WP_SITEURL: https://local.julienbonnier.dev/wp
      # This is used for Xdebug step debugging with PHP CLI and should match the "Name" of the server used in
      # PhpStorm server configuration: Settings > PHP > Servers > Name.
      # Note: When configured, it will also be used when step debugging from a browser but is necessary only for CLI.
      PHP_IDE_CONFIG: serverName=local (docker)
    env_file:
      - src/.env
  vite:
    image: node:22-slim
    environment:
      APP_URL: https://local.julienbonnier.dev/
      VITE_HMR_PROTOCOL: https
      VITE_HMR_HOST: local.julienbonnier.dev
      VITE_HMR_PORT: 443
    networks:
      - php
    volumes:
      - ./.docker/vite/entrypoint.sh:/bin/docker-entrypoint
      - ./src/web/app/themes/sage:/app
    user: node
    working_dir: /app
    entrypoint: ['bash', '-c', 'npm install && npx vite -c vite.config.dev.js']
    stop_signal: SIGKILL
